### ISSUE TITLE
Create CSS-only Timeline

### ISSUE THREAD

**Issue by honeysilvas** [blastpad/BlastPad_UI#12]
Create a CSS-only timeline.

All styles should be CSS only (no JavaScript). 

This is a good first bug and can be a mentored bug. Please message me here if you have questions.

**Comment by mmBabol** [comment]
Hi @honeysilvas , I created a CSS-only timeline with PR #26 , let me know if it's good or I should change something

**Comment by honeysilvas** [comment]
Hi @mmBabol!  

Everything looks good so far.  I'll let you know if I see anything that needs to be changed.

Good work.  Thanks so much!
