### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by honeysilvas** [blastpad/BlastPad_UI#14]
Logo design for BlastPad UI.

**Comment by Parthipan-Natkunam** [comment]
Hi @honeysilvas , may I take up this task. My skill level is that of a beginner but I am eager in becoming a contributor. Please let me know if I could start with it and also any concepts that you already have in mind for the logo, if any. 
My portfolio for sample work: [here](http://parthipan.co.in/)
the **graphics design tab** in portfolio section has my previous works related to this task.
Thanks.

**Comment by Parthipan-Natkunam** [comment]
I have made a pull request for this issue. Thanks.

**Comment by honeysilvas** [comment]
@Parthipan-Natkunam 

Great job!  This is awesome, thank you so much!  I accepted your pull request for this.

**Comment by Parthipan-Natkunam** [comment]
@honeysilvas 
Thank you :)
