### ISSUE TITLE
NPM installation

### ISSUE THREAD

**Issue by Shaun2D2** [blastpad/BlastPad_UI#20]
@honeysilvas I'm back, didn't have time for hacktoberfest but I want to get my 24 pull requests in for december :)

What do you think about adding this to NPM for quick installation?  Maybe even bower?

Cheers,
Shaun

**Comment by honeysilvas** [comment]
Hi, @Shaun2D2 !  Sounds good.  Nice to have you.

Re: NPM for quick installation and bower, that would be great.   Go for it!

**Comment by Shaun2D2** [comment]
@honeysilvas blast pad is now officially on NPM!

https://www.npmjs.com/package/blastpad-ui

submitted pull request that has the package.json file.

**Comment by honeysilvas** [comment]
@Shaun2D2 This is awesome!  Thank you so much!  

Can you add me as admin/collaborator on npm so I can access that page as well?  My username is honeysilvas.  Thanks!

Also, don't forget to modify the Readme.MD file to add your name as a contributor.

**Comment by Shaun2D2** [comment]
@honeysilvas done deal, your on it!

**Comment by honeysilvas** [comment]
Thanks!
